[versions]
activityCompose = "1.10.1" # TODO: Update to 1.11.0 or later after we bump compileSdk to 36
adaptive = "1.2.0"
agp = "8.13.0" # Delete this to-do on agp 9+ after searching and checking the project for the following: TODO[AGP9
androidLogin = "3.1.11"
androidxCollection = "1.5.0"
androidxCore = "1.16.0" # TODO: Update to 1.17.0 or later after we bump compileSdk to 36
appUpdateVersion = "2.1.0"
appcompat = "1.7.1"
biometricKtx = "1.2.0-alpha05"
coil = "3.3.0"
coil2 = "2.7.0" # Coil2 is used in old Legacy modules only
composeBom = "2025.12.00"
concurrentFuturesKtx = "1.3.0"
constraintLayout = "2.2.1"
coordinatorLayout = "1.3.0"
coreKtx = "1.7.0"
datastorePreferences = "1.2.0"
dotlottie = "0.12.2"
espressoCore = "3.7.0"
firebaseMessaging = "24.1.2"
gson = "2.13.2"
hiltAndroid = "2.57.2"
hiltAndroidx = "1.3.0"
integrity = "1.6.0"
#noinspection NewerVersionAvailable
junit = "4.13" # Don't update this because it breaks tests
junitAndroidx = "1.3.0"
kotest = "6.0.7"
kotlinxCoroutines = "1.10.2"
kotlinxSerialization = "1.9.0"
kotlin = "2.2.0" # Keep the same version as the one in Realm-Kotlin
ksp = "2.2.0-2.0.2" # Keep the same version as the one in Realm-Kotlin
ktlintPlugin = "14.0.1"
ktor = "3.3.3"
lifecycleRuntimeKtx = "2.10.0"
lottie = "6.7.1"
material = "1.13.0"
matomo = "4.3.4"
mockk = "1.14.6"
navigation = "2.9.6"
okhttp = "5.3.2"
okio = "3.16.2"
playReview = "2.0.2"
progressButton = "2.1.0"
recyclerView = "1.4.0"
#noinspection NewerVersionAvailable
robolectric = "4.13" # Don't update this because it breaks tests
room = "2.8.4"
sentry = "8.27.1"
sentryPlugin = "5.12.2"
splitties = "3.0.0"
stethoOkhttp3 = "1.6.0"
swipeRefreshLayout = "1.2.0"
workManager = "2.11.0"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
android-login = { module = "com.github.infomaniak:android-login", version.ref = "androidLogin" }
androidx-adaptive = { module = "androidx.compose.material3.adaptive:adaptive", version.ref = "adaptive" }
androidx-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout", version.ref = "adaptive" }
androidx-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation", version.ref = "adaptive" }
androidx-collection = { module = "androidx.collection:collection", version.ref = "androidxCollection" }
androidx-concurrent-futures-ktx = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "concurrentFuturesKtx" }
androidx-core = { module = "androidx.core:core", version.ref = "androidxCore" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerView" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "workManager" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "workManager" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "appcompat" }
biometric-ktx = { module = "androidx.biometric:biometric-ktx", version.ref = "biometricKtx" }
coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil" }
coil-two = { module = "io.coil-kt:coil", version.ref = "coil2" }
coil-two-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil2" }
coil-video = { module = "io.coil-kt.coil3:coil-video", version.ref = "coil" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-core" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-android = { module = "androidx.compose.ui:ui-android" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorLayout" }
firebase-messaging-ktx = { module = "com.google.firebase:firebase-messaging-ktx", version.ref = "firebaseMessaging" }
foundation-android = { module = "androidx.compose.foundation:foundation-android" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
hilt-androidx-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltAndroidx" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltAndroidx" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltAndroidx" }
infomaniak-core-appintegrity = { module = "com.infomaniak.core:AppIntegrity" }
infomaniak-core-auth = { module = "com.infomaniak.core:Auth" }
infomaniak-core-avatar = { module = "com.infomaniak.core:Avatar" }
infomaniak-core-coil = { module = "com.infomaniak.core:Coil" }
infomaniak-core-common = { module = "com.infomaniak.core:Common" }
infomaniak-core-crossapplogin = { module = "com.infomaniak.core:CrossAppLogin.Front" }
infomaniak-core-crossapplogin-back = { module = "com.infomaniak.core:CrossAppLogin.Back" }
infomaniak-core-crossapplogin-front = { module = "com.infomaniak.core:CrossAppLogin.Front" }
infomaniak-core-filetypes = { module = "com.infomaniak.core:FileTypes" }
infomaniak-core-fragmentnavigation = { module = "com.infomaniak.core:FragmentNavigation" }
infomaniak-core-inappreview = { module = "com.infomaniak.core:InAppReview" }
infomaniak-core-inappupdate = { module = "com.infomaniak.core:InAppUpdate" }
infomaniak-core-ksuite = { module = "com.infomaniak.core:KSuite" }
infomaniak-core-ksuite-myksuite = { module = "com.infomaniak.core:KSuite.MyKSuite" }
infomaniak-core-ksuite-pro = { module = "com.infomaniak.core:KSuite.KSuitePro" }
infomaniak-core-ktor = { module = "com.infomaniak.core:Ktor" }
infomaniak-core-matomo = { module = "com.infomaniak.core:Matomo" }
infomaniak-core-network = { module = "com.infomaniak.core:Network" }
infomaniak-core-notifications = { module = "com.infomaniak.core:Notifications" }
infomaniak-core-onboarding = { module = "com.infomaniak.core:Onboarding" }
infomaniak-core-recyclerview = { module = "com.infomaniak.core:RecyclerView" }
infomaniak-core-sentry = { module = "com.infomaniak.core:Sentry" }
infomaniak-core-sharedvalues = { module = "com.infomaniak.core:SharedValues" }
infomaniak-core-thumbnails = { module = "com.infomaniak.core:Thumbnails" }
infomaniak-core-twofactorauth-back = { module = "com.infomaniak.core:TwoFactorAuth.Back.WithUserDb" }
infomaniak-core-twofactorauth-front = { module = "com.infomaniak.core:TwoFactorAuth.Front" }
infomaniak-core-ui = { module = "com.infomaniak.core:Ui" }
infomaniak-core-ui-compose-accountbottomsheet = { module = "com.infomaniak.core:Ui.Compose.AccountBottomSheet" }
infomaniak-core-ui-compose-basicbutton = { module = "com.infomaniak.core:Ui.Compose.BasicButton" }
infomaniak-core-ui-compose-basics = { module = "com.infomaniak.core:Ui.Compose.Basics" }
infomaniak-core-ui-compose-bottomstickybuttonscaffolds = { module = "com.infomaniak.core:Ui.Compose.BottomStickyButtonScaffolds" }
infomaniak-core-ui-compose-margin = { module = "com.infomaniak.core:Ui.Compose.Margin" }
infomaniak-core-ui-compose-materialthemefromxml = { module = "com.infomaniak.core:Ui.Compose.MaterialThemeFromXml" }
infomaniak-core-ui-compose-preview = { module = "com.infomaniak.core:Ui.Compose.Preview" }
infomaniak-core-ui-compose-theme = { module = "com.infomaniak.core:Ui.Compose.Theme" }
infomaniak-core-ui-view-edgetoedge = { module = "com.infomaniak.core:Ui.View.EdgeToEdge" }
infomaniak-core-webview = { module = "com.infomaniak.core:WebView" }
integrity = { module = "com.google.android.play:integrity", version.ref = "integrity" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-serialization-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "kotlinxSerialization" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "kotlinxSerialization" }
ktor-client-content-negociation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-client-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
dotlottie = { module = "com.github.lottiefiles:dotlottie-android", version.ref = "dotlottie" }
material = { module = "com.google.android.material:material", version.ref = "material" }
matomo = { module = "com.github.matomo-org:matomo-sdk-android", version.ref = "matomo" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-safeargs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
play-app-update = { module = "com.google.android.play:app-update", version.ref = "appUpdateVersion" }
play-app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdateVersion" }
play-review = { module = "com.google.android.play:review", version.ref = "playReview" }
play-review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "playReview" }
progress-button = { module = "com.github.razir.progressbutton:progressbutton", version.ref = "progressButton" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
sentry-android = { module = "io.sentry:sentry-android", version.ref = "sentry" }
sentry-android-fragment = { module = "io.sentry:sentry-android-fragment", version.ref = "sentry" }
sentry-okhttp = { module = "io.sentry:sentry-okhttp", version.ref = "sentry" }
splitties-appctx = { module = "com.louiscad.splitties:splitties-appctx", version.ref = "splitties" }
splitties-bitflags = { module = "com.louiscad.splitties:splitties-bitflags", version.ref = "splitties" }
splitties-bundle = { module = "com.louiscad.splitties:splitties-bundle", version.ref = "splitties" }
splitties-collections = { module = "com.louiscad.splitties:splitties-collections", version.ref = "splitties" }
splitties-coroutines = { module = "com.louiscad.splitties:splitties-coroutines", version.ref = "splitties" }
splitties-intents = { module = "com.louiscad.splitties:splitties-intents", version.ref = "splitties" }
splitties-mainhandler = { module = "com.louiscad.splitties:splitties-mainhandler", version.ref = "splitties" }
splitties-mainthread = { module = "com.louiscad.splitties:splitties-mainthread", version.ref = "splitties" }
splitties-systemservices = { module = "com.louiscad.splitties:splitties-systemservices", version.ref = "splitties" }
splitties-toast = { module = "com.louiscad.splitties:splitties-toast", version.ref = "splitties" }
stetho-okhttp3 = { module = "com.facebook.stetho:stetho-okhttp3", version.ref = "stethoOkhttp3" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swipeRefreshLayout" }
# Tests
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitAndroidx" }
androidx-rules = { module = "androidx.test:rules", version.ref = "coreKtx" }
androidx-runner = { module = "androidx.test:runner", version.ref = "coreKtx" }
androidx-test-core = { module = "androidx.test:core", version.ref = "coreKtx" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "coreKtx" }
junit = { module = "junit:junit", version.ref = "junit" }
mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "kotlin-parcelize" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPlugin" }
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
sentry-plugin = { id = "io.sentry.android.gradle", version.ref = "sentryPlugin" }
